import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["Hanken Grotesk", "-apple-system", "BlinkMacSystemFont", "Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "monospace"],
        // Design-system type roles (see /design/DESIGN.md)
        "headline-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "body-lg-mobile": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "label-caps": ["JetBrains Mono"],
        "display-time": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "34px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["17px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg-mobile": ["16px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-time": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "500" }],
      },
      spacing: {
        "container-padding": "20px",
        "element-gap": "12px",
        "bubble-padding-x": "16px",
        "bubble-padding-y": "12px",
        "section-margin": "32px",
      },
      colors: {
        // ---- Stitch design-system tokens (source of truth: /design/DESIGN.md) ----
        surface: "#101226",
        "surface-dim": "#101226",
        "surface-bright": "#36384e",
        "surface-container-lowest": "#0a0c20",
        "surface-container-low": "#181a2e",
        "surface-container": "#1c1e33",
        "surface-container-high": "#26283e",
        "surface-container-highest": "#313349",
        "surface-variant": "#313349",
        "surface-tint": "#3dd8f4",
        "on-surface": "#e0e0fd",
        "on-surface-variant": "#bbc9cd",
        "inverse-surface": "#e0e0fd",
        "inverse-on-surface": "#2d2f44",
        outline: "#869397",
        "outline-variant": "#3c494c",
        primary: "#cbf5ff",
        "on-primary": "#00363f",
        "primary-container": "#4de3ff",
        "on-primary-container": "#006371",
        "inverse-primary": "#006877",
        "primary-fixed": "#a5eeff",
        "primary-fixed-dim": "#3dd8f4",
        secondary: "#3fe881",
        "on-secondary": "#003919",
        "secondary-container": "#00cb68",
        "on-secondary-container": "#004f24",
        "secondary-fixed": "#61ff97",
        "secondary-fixed-dim": "#36e27c",
        tertiary: "#ececff",
        "on-tertiary": "#252d5b",
        "tertiary-container": "#c8ceff",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#101226",
        "on-background": "#e0e0fd",
        // Live-status green — reserved for the header/live dot only.
        live: "#33E07A",
        // ---- Existing aurora/brain palette ----
        aurora: {
          base: "#02040f",
          deep: "#080820",
          mid: "#150e28",
          haze: "#0c1830",
        },
        silas: {
          node: "rgba(195,220,245,0.55)",
          bright: "rgba(245,250,255,0.98)",
          bubble: "rgba(8,12,28,0.42)",
          border: "rgba(180,210,255,0.13)",
          text: "rgba(232,240,250,0.96)",
        },
      },
      borderRadius: {
        "20": "20px",
        "24": "24px",
      },
    },
  },
  plugins: [],
};

export default config;
